#!/bin/bash
[ -n "$TMPDIR" ] || TMPDIR=/tmp
shared_dir=$TMPDIR/talk_global
[ -d $shared_dir ] || mkdir -m 777 $shared_dir
tuser="$(whoami)"
[ -d $shared_dir/$tuser ] || mkdir -m 777 $shared_dir/$tuser
[ -f $shared_dir/sync ] || { touch $shared_dir/sync; chmod 777 $shared_dir/sync; }
[ -f $shared_dir/history ] || { touch $shared_dir/history; chmod 777 $shared_dir/history; }
exit_program() {
	rm -rf $shared_dir/$tuser
}
history_msg() {
	cat $shared_dir/history | grep -v "^${tuser} .*" | tail -n 1
}
current_msg() {
	cat $shared_dir/sync | grep -v "^${tuser} .*" | tail -n 1
}
get_msg() {
	cat $shared_dir/${juid}/$(cat $shared_dir/sync | grep -v "^${tuser} .*" | tail -n 1 | cut -d " " -f 2)
}
writemsg() {
	read -p "$(echo -e "\e[0;32m")> $(echo -e "\e[0m")" await_msg
	ttemp="$(mktemp -p $shared_dir/$tuser)"
	echo "$tuser $(echo $ttemp | grep -o "[^/]*$")" >> $shared_dir/sync
	echo "$await_msg" > $ttemp; chmod 777 $ttemp
	writemsg
}
trap exit_program EXIT
echo "talk-global v1"
while true; do
	if [ -z "$(cat $shared_dir/sync | grep -v "^${tuser} .*")" ]; then continue; fi
	if [ "$(history_msg)" != "$(current_msg)" ]; then
		juid="$(cat $shared_dir/sync | grep -v "^${tuser} .*" | tail -n 1 | cut -d " " -f 1)"
		echo -e "\n\e[0;33m${juid}: \e[0m$(get_msg)"
	       	echo -e -n "\e[0;32m> \e[0m"
		sleep 0.1
		cat $shared_dir/sync | grep -v "^${tuser} .*" | tail -n 1 >> $shared_dir/history
	else :; fi
done < <(writemsg)
